# Используем базовый образ python
FROM python:3.9-slim

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы
COPY . /app

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл .env
COPY .env /app/.env

# Устанавливаем переменные окружения
ENV OPENAI_API_KEY=${OPENAI_API_KEY}
ENV TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
ENV API_URL=${API_URL}

# Команда для запуска сервиса
CMD ["python", "bot.py"]
