services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydatabase
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mynetwork

  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: "fastapi"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DAILY_MESSAGE_LIMIT=${DAILY_MESSAGE_LIMIT}  # Добавляем переменную окружения
      - DATABASE_URL=postgresql://myuser:mypassword@postgres/mydatabase
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    networks:
      - mynetwork

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: "telegram-bot"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=${API_URL}
    depends_on:
      - fastapi
    networks:
      - mynetwork

networks:
  mynetwork:

volumes:
  postgres_data:
