services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  postgres:
    image: "postgres:latest"
    container_name: "postgres"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: dbname
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: "fastapi"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - DAILY_MESSAGE_LIMIT=${DAILY_MESSAGE_LIMIT}
      - DATABASE_URL=${DATABASE_URL}
    ports:
      - "5000:5000"
    depends_on:
      - redis
      - postgres
    networks:
      - mynetwork

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: "telegram-bot"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=${API_URL}
    depends_on:
      - fastapi
    networks:
      - mynetwork

networks:
  mynetwork:
