FROM python:3.9-slim

# Устанавливаем зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Копируем остальные файлы
COPY . /app

# Устанавливаем рабочую директорию
WORKDIR /app

# Копируем файл .env
COPY .env /app/.env

# Команда для запуска сервиса
CMD ["python", "bot.py"]
