services:
  redis:
    image: "redis:latest"
    container_name: "redis"
    ports:
      - "6379:6379"
    networks:
      - mynetwork

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: "fastapi"
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    ports:
      - "5000:5000"
    depends_on:
      - redis
    networks:
      - mynetwork

  telegram-bot:
    build:
      context: .
      dockerfile: Dockerfile.bot
    container_name: "telegram-bot"
    environment:
      - TELEGRAM_TOKEN=${TELEGRAM_TOKEN}
      - API_URL=${API_URL}
    depends_on:
      - fastapi
    networks:
      - mynetwork

networks:
  mynetwork:
